### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Haze-sh** [Haze-sh/dotfiles#1]
- [x] Minimize neovim configuration
- [x] Minimize sway configuration (wofi, bemenu and flavours parts)
- [x] Edit zsh config
- [x] scripts
     - [x] gammastep
     - [x] annotations
     - [x] hypothesis
     - [x] Remove bashisms
- [x] Remove paths dependencies
- [x] Waybar 
     - [x] icons edit
     - [x] Bar size edit
     - [x] custom module edit
- [x] Wofi / Rofi configuration & themes
- [ ] Make dotfiles cross-platform
     - [ ] NixOS
     - [ ] Gentoo
     - [ ] Windows
     - [ ] macOS
- [x] Add keybindings documentation
